### PR TITLE
url-editor-input mixin

### PR DESCRIPTION
**Pull request by nazartokar**

### CODE REVIEW

**Review by jarrodek — COMMENTED** [review]
Why are you changing this? I though you don't use URL editor?

**Comment by nazartokar** [comment]
@jarrodek well, we currently have this field and need to redesign it. I guess alter it can be replaced with a dropdown but currently there's a redesign task.

**Comment by jarrodek** [comment]
@nazartokar  That is why I've added an option for the API console to disable the URL editor in the view. You can put any type of an input element above the console that will mimic the URL editor.

**Comment by nazartokar** [comment]
@jarrodek ok but now there is a text input and I need to style it.

**Comment by jarrodek** [comment]
This is not an answer @nazartokar. I have to reach to Anton because this shouldn't happen.
Although, I'm merging this to not block you.

**Comment by nazartokar** [comment]
@jarrodek thank you. I guess we can have scenarios where we'll have text field or dropdown in different places. So let's better have them both customizable.

**Pull request merged**
